{% set name = "jeepney" %}
{% set version = "0.7.0" %}
{% set sha256 = "1237cd64c8f7ac3aa4b3f332c4d0fb4a8216f39eaa662ec904302d4d77de5a54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: flit install --deps none

requirements:
  host:
    - python >=3.5
    - flit
  run:
    - python >=3.5

test:
  imports:
    - jeepney

about:
  home: https://gitlab.com/takluyver/jeepney
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python DBus interface
  description: |
    This is a low-level, pure Python DBus protocol client. It has
    an I/O-free core, and integration modules for different event
    loops.
  doc_url: https://jeepney.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/takluyver/jeepney

extra:
  recipe-maintainers:
    - ccordoba12
    - takluyver
